# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-26 02:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '\u041d\u043e\u0432\u043e\u0441\u0442\u044c'},
        ),
    ]
